language: c

matrix:
  include:
    - compiler: gcc
      env: CFLAGS="-std=gnu99"
    - compiler: clang
      env: CFLAGS="-std=gnu99"
      # test that we can compile on old compilers.
    - compiler: gcc
      env: CFLAGS="-std=c89 -Wno-endif-labels -D_POSIX_C_SOURCE=200809L -D_DEFAULT_SOURCE -D_BSD_SOURCE -Wno-comment"

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

before_script:
  - cmake --version

script:
  - mkdir cibuild
  - cd cibuild
  - cmake .. && make -j VERBOSE=1
  - ./test/unittest/unabto_unittest
