language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      env: CFLAGS="-std=gnu99"
    - os: linux
      compiler: clang
      env: CFLAGS="-std=gnu99"
      # test that we can compile on old compilers.
    - os: linux
      compiler: clang
      env: CFLAGS="-std=c89 -Wno-endif-labels -D_POSIX_C_SOURCE=200809L -D_DEFAULT_SOURCE -D_BSD_SOURCE -Wno-comment"
    - os: osx
      osx_image: xcode9.1

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

before_script:
  - cmake --version

script:
  - mkdir cibuild
  - cd cibuild
  - cmake .. && make -j VERBOSE=1
  - ./test/unittest/unabto_unittest
  - mkdir -p bin
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp linux64/unabto/apps/tunnel/unabto_tunnel bin/unabto_tunnel_linux; fi;
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp mac/unabto/apps/tunnel/unabto_tunnel bin/unabto_tunnel_osx; fi;

deploy:
  provider: releases
  api_key:
    secure: wDgmZWEIp9YqVIaE/RvDqG6CdENT9+omuUuavEf3ttHS8eOJSp4XUxvLZnNqLMS7mjA36uLFwAxlQ2/b7R4IIRf/v0L9zc24yUbuff2pZUxyfYHq9UVJtsm/KWEgBs8X+oinCVBevoGx1HyvNARf4Jt2jtFW2kOYyJGWugRhInWE7wRx/bTch5eMhw80E97ATQlcnb9dtnQa4I1mkYty0qwO3n+LQbyDMpEF6vHk4z/7vaCehIOofFAJJwDv5Trci3qzr/Z3kgfD6ZUXefa1ffh3LuxY8kAmkHea2Gp1G2rFr/Uotus1t89klrskMZHb7Y/ci2kWcU9S8o7NXInn7+hN5t/AYSeY/gPyYo9ZIePYOJLXoip3B2yvXJPD+b4ImOEot2faiqj2p6x9F4gIbaoXRKXsZeHV+MKVTD8W3E6IPFU/6wWr4V/VBeNtn2tgew51s84/Q/VaoJJqxSHisNZhY28rK3tQkX0fZXRH7HH3SQm8p5XMPL7sEr1X7FcGsi6jLCZYWB4ZDK3Ts32ULsyS5Fcnq77uPwHQVOwy/FY/W8Bj7N8qUQEDopdXU57R++uh6IqG23HIP7B/iAHEn2MGYhbh4k5Y1ZaGkRuhnv19nvp899WsLdYxA3JWVYhkhuCPJswMjyF0ddKUf7ZPVm6aehSN9AXipYvddlzY86I=
  file:
    - bin/unabto_tunnel_linux
    - bin/unabto_tunnel_mac
  on:
    repo: nabto/unabto
