version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    mkdir builddir || exit 1
    cd builddir || exit 1
    cmake -DCMAKE_BUILD_TYPE=Release --config Release .. || exit 1
    cmake --build . --config Release || exit 1
    test\unittest\Release\unabto_unittest.exe || exit 1
    
artifacts:
- path: builddir\apps\tunnel\Release\unabto_tunnel.exe
  name: unabto_tunnel
deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: /ZS7w9J1/2S5ise/ZkEA/aig3ASgfNwS6uiPCMHlg4s6AH1+RPF0UY1FcP784Gyv
  artifact: /unabto_tunnel.exe/
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true
